"""Initial model

Revision ID: 8444da9e93b2
Revises: None
Create Date: 2016-07-28 00:49:42.846213

"""

# revision identifiers, used by Alembic.
revision = '8444da9e93b2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_state',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('number_of_images', sa.Integer(), nullable=True),
    sa.Column('downloading_image', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('url')
    )
    op.create_table('slide',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('slideshare_url', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('_hash', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('slideshare_url')
    )
    op.create_table('user',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('fb_id', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fb_id')
    )
    op.create_table('users_slides',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('slide_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['slide_id'], ['slide.idx'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.idx'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_slides')
    op.drop_table('user')
    op.drop_table('slide')
    op.drop_table('download_state')
    ### end Alembic commands ###
